-- StockDone core PostgreSQL schema
CREATE TABLE IF NOT EXISTS businesses (id UUID PRIMARY KEY, name TEXT NOT NULL, phone TEXT, address TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS branches (id UUID PRIMARY KEY, business_id UUID NOT NULL REFERENCES businesses(id), name TEXT NOT NULL, code TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(business_id,code));
CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY, business_id UUID NOT NULL REFERENCES businesses(id), username TEXT NOT NULL, name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('owner','manager','cashier')), password_hash TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(business_id,username));
CREATE TABLE IF NOT EXISTS categories (id UUID PRIMARY KEY, business_id UUID NOT NULL REFERENCES businesses(id), name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS products (id UUID PRIMARY KEY, business_id UUID NOT NULL REFERENCES businesses(id), name TEXT NOT NULL, sku TEXT NOT NULL, category_id UUID REFERENCES categories(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(business_id,sku));
CREATE TABLE IF NOT EXISTS product_variants (id UUID PRIMARY KEY, product_id UUID NOT NULL REFERENCES products(id), size TEXT, color TEXT, barcode TEXT, cost NUMERIC(12,2) NOT NULL DEFAULT 0, price NUMERIC(12,2) NOT NULL DEFAULT 0, UNIQUE(product_id,barcode));
CREATE TABLE IF NOT EXISTS inventory (id UUID PRIMARY KEY, branch_id UUID NOT NULL REFERENCES branches(id), variant_id UUID NOT NULL REFERENCES product_variants(id), quantity INTEGER NOT NULL DEFAULT 0, reorder_level INTEGER NOT NULL DEFAULT 5, UNIQUE(branch_id,variant_id));
CREATE TABLE IF NOT EXISTS stock_movements (id UUID PRIMARY KEY, branch_id UUID NOT NULL REFERENCES branches(id), variant_id UUID NOT NULL REFERENCES product_variants(id), type TEXT NOT NULL, quantity INTEGER NOT NULL, reason TEXT, reference_id UUID, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS suppliers (id UUID PRIMARY KEY,business_id UUID NOT NULL REFERENCES businesses(id),name TEXT NOT NULL,phone TEXT,address TEXT);
CREATE TABLE IF NOT EXISTS purchases (id UUID PRIMARY KEY,business_id UUID NOT NULL REFERENCES businesses(id),branch_id UUID NOT NULL REFERENCES branches(id),supplier_id UUID REFERENCES suppliers(id),invoice_no TEXT NOT NULL,purchase_date TIMESTAMPTZ NOT NULL DEFAULT now(),total NUMERIC(12,2) NOT NULL DEFAULT 0,payment_method TEXT NOT NULL DEFAULT 'credit',paid_amount NUMERIC(12,2) NOT NULL DEFAULT 0,UNIQUE(business_id,invoice_no));
CREATE TABLE IF NOT EXISTS purchase_items (id UUID PRIMARY KEY,purchase_id UUID NOT NULL REFERENCES purchases(id),variant_id UUID NOT NULL REFERENCES product_variants(id),quantity INTEGER NOT NULL,cost NUMERIC(12,2) NOT NULL);
CREATE TABLE IF NOT EXISTS supplier_transactions (id UUID PRIMARY KEY,business_id UUID NOT NULL REFERENCES businesses(id),supplier_id UUID NOT NULL REFERENCES suppliers(id),type TEXT NOT NULL CHECK(type IN ('purchase','payment')),amount NUMERIC(12,2) NOT NULL,reference_id UUID,note TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_supplier_transactions_supplier_date ON supplier_transactions(supplier_id,created_at DESC);

CREATE TABLE IF NOT EXISTS sales (id UUID PRIMARY KEY,business_id UUID NOT NULL REFERENCES businesses(id),branch_id UUID NOT NULL REFERENCES branches(id),invoice_no TEXT NOT NULL,customer_id UUID,subtotal NUMERIC(12,2) NOT NULL,discount NUMERIC(12,2) NOT NULL DEFAULT 0,total NUMERIC(12,2) NOT NULL,payment_method TEXT NOT NULL,client_reference UUID,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(business_id,invoice_no));
CREATE TABLE IF NOT EXISTS payments (id UUID PRIMARY KEY,business_id UUID NOT NULL REFERENCES businesses(id),branch_id UUID NOT NULL REFERENCES branches(id),sale_id UUID NOT NULL REFERENCES sales(id),method TEXT NOT NULL,amount NUMERIC(12,2) NOT NULL,received NUMERIC(12,2) NOT NULL DEFAULT 0,change_amount NUMERIC(12,2) NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_payments_sale ON payments(sale_id,created_at DESC);
CREATE TABLE IF NOT EXISTS sale_items (id UUID PRIMARY KEY,sale_id UUID NOT NULL REFERENCES sales(id),variant_id UUID NOT NULL REFERENCES product_variants(id),quantity INTEGER NOT NULL,unit_price NUMERIC(12,2) NOT NULL,unit_cost NUMERIC(12,2) NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_inventory_variant ON inventory(variant_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_variant_date ON stock_movements(variant_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_sku ON products(business_id,sku);
CREATE INDEX IF NOT EXISTS idx_variants_barcode ON product_variants(barcode);

CREATE TABLE IF NOT EXISTS customers (id UUID PRIMARY KEY,business_id UUID NOT NULL REFERENCES businesses(id),name TEXT NOT NULL,phone TEXT,address TEXT,balance NUMERIC(12,2) NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS customer_transactions (id UUID PRIMARY KEY,customer_id UUID NOT NULL REFERENCES customers(id),type TEXT NOT NULL CHECK(type IN ('credit_sale','payment','debit_adjustment','credit_adjustment')),amount NUMERIC(12,2) NOT NULL,reference_id UUID,note TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_customer_transactions_customer_date ON customer_transactions(customer_id,created_at DESC);

CREATE TABLE IF NOT EXISTS returns (id UUID PRIMARY KEY,business_id UUID NOT NULL REFERENCES businesses(id),branch_id UUID NOT NULL REFERENCES branches(id),sale_id UUID NOT NULL REFERENCES sales(id),type TEXT NOT NULL CHECK(type IN ('return','exchange')),refund_amount NUMERIC(12,2) NOT NULL DEFAULT 0,price_difference NUMERIC(12,2) NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS return_items (id UUID PRIMARY KEY,return_id UUID NOT NULL REFERENCES returns(id),variant_id UUID NOT NULL REFERENCES product_variants(id),quantity INTEGER NOT NULL,unit_price NUMERIC(12,2) NOT NULL,unit_cost NUMERIC(12,2) NOT NULL DEFAULT 0,direction TEXT NOT NULL DEFAULT 'in' CHECK(direction IN ('in','out')));
CREATE INDEX IF NOT EXISTS idx_returns_sale ON returns(sale_id,created_at DESC);
CREATE TABLE IF NOT EXISTS return_payments (id UUID PRIMARY KEY,business_id UUID NOT NULL REFERENCES businesses(id),branch_id UUID NOT NULL REFERENCES branches(id),return_id UUID NOT NULL REFERENCES returns(id),method TEXT NOT NULL CHECK(method IN ('cash','card','bank','other')),direction TEXT NOT NULL CHECK(direction IN ('refund','received')),amount NUMERIC(12,2) NOT NULL CHECK(amount > 0),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_return_payments_return ON return_payments(return_id,created_at DESC);\nCREATE TABLE IF NOT EXISTS backup_metadata (id UUID PRIMARY KEY,business_id UUID NOT NULL REFERENCES businesses(id),created_by UUID REFERENCES users(id),storage_key TEXT NOT NULL,checksum TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),expires_at TIMESTAMPTZ);\nCREATE INDEX IF NOT EXISTS idx_backup_metadata_business_date ON backup_metadata(business_id,created_at DESC);

CREATE TABLE IF NOT EXISTS audit_logs (id UUID PRIMARY KEY,business_id UUID NOT NULL REFERENCES businesses(id),user_id UUID REFERENCES users(id),action TEXT NOT NULL,entity TEXT,entity_id UUID,details JSONB,ip_address INET,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_audit_logs_business_date ON audit_logs(business_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity,entity_id,created_at DESC);
