import JsBarcode from "jsbarcode";

export function barcodeSvg(barcode:string){const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");JsBarcode(svg,barcode,{format:"CODE128",displayValue:true,fontSize:14,height:70,margin:8});return new XMLSerializer().serializeToString(svg)}

export function barcodeLabelHtml(name:string,sku:string,barcode:string,price:number){const svg=barcodeSvg(barcode);return `<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Arial;margin:0}.label{width:300px;padding:10px;text-align:center}.name{font-weight:700;font-size:14px}.barcode{margin:4px auto}.price{font-size:18px;font-weight:700}</style></head><body><div class="label"><div class="name">${name}</div><div>SKU: ${sku}</div><div class="barcode">${svg}</div><div class="price">Rs. ${price}</div></div><script>window.onload=()=>window.print()</script></body></html>`}
export type BarcodePrintOptions={columns?:number,labelWidthMm?:number,labelHeightMm?:number,quantity?:number};
export function barcodeBatchHtml(name:string,sku:string,barcode:string,price:number,options:BarcodePrintOptions={}){const columns=Math.max(1,Math.min(5,options.columns??2));const qty=Math.max(1,Math.min(500,options.quantity??1));const labels=Array.from({length:qty},()=>`<div class="label"><div class="name">${name}</div><div>SKU: ${sku}</div><div class="barcode">${barcodeSvg(barcode)}</div><div class="price">Rs. ${price}</div></div>`).join("");return `<!doctype html><html><head><meta charset="utf-8"><style>@page{margin:4mm}body{font-family:Arial;margin:0}.sheet{display:grid;grid-template-columns:repeat(${columns},1fr);gap:2mm}.label{text-align:center;border:1px dashed #999;padding:3mm;break-inside:avoid;min-height:${options.labelHeightMm??30}mm}.name{font-weight:700;font-size:12px;white-space:nowrap;overflow:hidden}.barcode{margin:2px auto}.barcode svg{max-width:100%;height:auto}.price{font-size:15px;font-weight:700}</style></head><body><div class="sheet">${labels}</div><script>window.onload=()=>window.print()</script></body></html>`}
export function printBarcodeBatch(name:string,sku:string,barcode:string,price:number,options:BarcodePrintOptions={}){const w=window.open("","_blank","width=900,height=700");if(w){w.document.write(barcodeBatchHtml(name,sku,barcode,price,options));w.document.close()}}
export function printBarcodeLabel(name:string,sku:string,barcode:string,price:number){printBarcodeBatch(name,sku,barcode,price,{columns:1,quantity:1,labelHeightMm:35})}

export function generateBarcode(prefix="SD"){const safe=prefix.replace(/[^A-Za-z0-9]/g,"").slice(0,6)||"SD";return safe+"-"+Date.now().toString().slice(-10)+Math.floor(Math.random()*90+10)}
export function generateBarcodeBatch(prefix="SD",count=1){const n=Math.max(1,Math.min(500,count));return Array.from({length:n},()=>generateBarcode(prefix))}
